name: Tests

on: [push, pull_request]

env:
  PYTHON_LATEST: "3.11"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.pythonLocation }}/bin/*
            ${{ env.pythonLocation }}/lib/*
            ${{ env.pythonLocation }}/scripts/*
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('setup.py', 'requirements.txt') }}
      - name: Install The Fuck with all dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          pip install -Ur requirements.txt coveralls
          python setup.py develop
      - name: Lint
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == env.PYTHON_LATEST
        run: flake8
      - name: Run tests
        uses: koenhagen/measure-energy-action@v0.33
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: coverage run --source=thefuck,tests -m pytest -v --capture=sys tests
          count: 1
      - name: Run tests (including functional)
        uses: koenhagen/measure-energy-action@v0.33
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            docker build -t thefuck/python3 -f tests/Dockerfile --build-arg PYTHON_VERSION=3 .
            docker build -t thefuck/python2 -f tests/Dockerfile --build-arg PYTHON_VERSION=2 .
            coverage run --source=thefuck,tests -m pytest -v --capture=sys tests --enable-functional
          count: 1
